-- MySQL Script generated by MySQL Workbench
-- qua 08 set 2021 17:35:08
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';


-- -----------------------------------------------------
-- Schema IRRF
-- -----------------------------------------------------
DROP DATABASE IF EXISTS `IFFR`;
CREATE SCHEMA IF NOT EXISTS `IRRF` ;
USE `IRRF` ;


-- -----------------------------------------------------
-- Table `IRRF`.`Bairros`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `IRRF`.`Bairros` ;

CREATE TABLE IF NOT EXISTS `IRRF`.`Bairros` (
  `idBairro` INT NOT NULL AUTO_INCREMENT,
  `nomeBairro` VARCHAR(255) NULL,
  PRIMARY KEY (`idBairro`));


-- -----------------------------------------------------
-- Table `IRRF`.`Ufs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `IRRF`.`Ufs` ;

CREATE TABLE IF NOT EXISTS `IRRF`.`Ufs` (
  `siglaUf` VARCHAR(45) NOT NULL,
  `nomeUf` VARCHAR(45) NULL,
  PRIMARY KEY (`siglaUf`));


-- -----------------------------------------------------
-- Table `IRRF`.`Cidades`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `IRRF`.`Cidades` ;

CREATE TABLE IF NOT EXISTS `IRRF`.`Cidades` (
  `idCidades` INT NOT NULL AUTO_INCREMENT,
  `nomeCidade` VARCHAR(255) NULL,
  `Ufs_siglaUf` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCidades`),
  INDEX `fk_Cidades_Ufs1_idx` (`Ufs_siglaUf` ASC) VISIBLE,
  CONSTRAINT `fk_Cidades_Ufs1`
    FOREIGN KEY (`Ufs_siglaUf`)
    REFERENCES `IRRF`.`Ufs` (`siglaUf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `IRRF`.`TipoLogradouro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `IRRF`.`TipoLogradouro` ;

CREATE TABLE IF NOT EXISTS `IRRF`.`TipoLogradouro` (
  `siglaLogradouro` VARCHAR(45) NOT NULL,
  `nomeTipoLogradouro` VARCHAR(45) NULL,
  PRIMARY KEY (`siglaLogradouro`));


-- -----------------------------------------------------
-- Table `IRRF`.`Logradouros`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `IRRF`.`Logradouros` ;

CREATE TABLE IF NOT EXISTS `IRRF`.`Logradouros` (
  `idLogradouro` INT NOT NULL AUTO_INCREMENT,
  `nomeLogradouro` VARCHAR(45) NULL,
  `TipoLogradouro_siglaLogradouro` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idLogradouro`),
  INDEX `fk_Logradouros_TipoLogradouro1_idx` (`TipoLogradouro_siglaLogradouro` ASC) VISIBLE,
  CONSTRAINT `fk_Logradouros_TipoLogradouro1`
    FOREIGN KEY (`TipoLogradouro_siglaLogradouro`)
    REFERENCES `IRRF`.`TipoLogradouro` (`siglaLogradouro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `IRRF`.`Endereco`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `IRRF`.`Endereco` ;

CREATE TABLE IF NOT EXISTS `IRRF`.`Endereco` (
  `idEndereco` INT NOT NULL AUTO_INCREMENT,
  `cep` VARCHAR(255) NOT NULL UNIQUE,
  `Bairros_idBairro` INT NOT NULL,
  `Cidades_idCidades` INT NOT NULL,
  `Logradouros_idLogradouro` INT NOT NULL,
  PRIMARY KEY (`idEndereco`),
  INDEX `fk_Endereco_Bairros_idx` (`Bairros_idBairro` ASC) VISIBLE,
  INDEX `fk_Endereco_Cidades_idx` (`Cidades_idCidades` ASC) VISIBLE,
  INDEX `fk_Endereco_Logradouros_idx` (`Logradouros_idLogradouro` ASC) VISIBLE,
  CONSTRAINT `fk_Endereco_Bairros`
    FOREIGN KEY (`Bairros_idBairro`)
    REFERENCES `IRRF`.`Bairros` (`idBairro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Endereco_Cidades`
    FOREIGN KEY (`Cidades_idCidades`)
    REFERENCES `IRRF`.`Cidades` (`idCidades`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Endereco_Logradouros`
    FOREIGN KEY (`Logradouros_idLogradouro`)
    REFERENCES `IRRF`.`Logradouros` (`idLogradouro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    );


-- -----------------------------------------------------
-- Table `IRRF`.`DDDs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `IRRF`.`DDDs` ;

CREATE TABLE IF NOT EXISTS `IRRF`.`DDDs` (
  `DDD` VARCHAR(32) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`DDD`));


-- -----------------------------------------------------
-- Table `IRRF`.`DDIs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `IRRF`.`DDIs` ;

CREATE TABLE IF NOT EXISTS `IRRF`.`DDIs` (
  `DDI` VARCHAR(32) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`DDI`));


-- -----------------------------------------------------
-- Table `IRRF`.`Fones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `IRRF`.`Fones` ;

CREATE TABLE IF NOT EXISTS `IRRF`.`Fones` (
  `idFone` INT NOT NULL AUTO_INCREMENT,
  `numero` VARCHAR(45) NOT NULL,
  `DDDs_DDD` VARCHAR(32) NOT NULL,
  `DDIs_DDI` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`idFone`),
  INDEX `fk_Fones_DDDs1_idx` (`DDDs_DDD` ASC) VISIBLE,
  INDEX `fk_Fones_DDIs1_idx` (`DDIs_DDI` ASC) VISIBLE,
  CONSTRAINT `fk_Fones_DDDs1`
    FOREIGN KEY (`DDDs_DDD`)
    REFERENCES `IRRF`.`DDDs` (`DDD`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Fones_DDIs1`
    FOREIGN KEY (`DDIs_DDI`)
    REFERENCES `IRRF`.`DDIs` (`DDI`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `IRRF`.`Contribuinte`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `IRRF`.`Contribuinte` ;

CREATE TABLE IF NOT EXISTS `IRRF`.`Contribuinte` (
  `idContribuinte` INT NOT NULL AUTO_INCREMENT,
  `nomeContribuinte` VARCHAR(255) NULL,
  `sobrenomeContribuinte` VARCHAR(255) NULL,
  `nomeSocialContribuinte` VARCHAR(255) NULL,
  `cpfContribuinte` VARCHAR(16) NOT NULL,
  `rgContribuinte` VARCHAR(16) NULL,
  `sexoContribuinte` CHAR(1) NULL,
  `numeroEnderecoContribuinte` INT NULL,
  `Endereco_idEndereco` INT NOT NULL,
  `complementoContribuinte` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idContribuinte`),
  INDEX `fk_Contribuinte_Endereco1_idx` (`Endereco_idEndereco` ASC) VISIBLE,
  UNIQUE INDEX `cpfContribuinte_UNIQUE` (`cpfContribuinte` ASC) VISIBLE,
  CONSTRAINT `fk_Contribuinte_Endereco1`
    FOREIGN KEY (`Endereco_idEndereco`)
    REFERENCES `IRRF`.`Endereco` (`idEndereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `IRRF`.`Empresas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `IRRF`.`Empresas` ;

CREATE TABLE IF NOT EXISTS `IRRF`.`Empresas` (
  `idEmpresa` INT NOT NULL AUTO_INCREMENT,
  `nomeEmpresa` VARCHAR(255) NOT NULL,
  `cnpjEmpresa` VARCHAR(32) NOT NULL,
  `complementoEmpresa` VARCHAR(255) NOT NULL,
  `numeroEnderecoEmpresa` INT NULL,
  `Endereco_idEndereco` INT NOT NULL,
  PRIMARY KEY (`idEmpresa`),
  UNIQUE INDEX `cnpjEmpresa_UNIQUE` (`cnpjEmpresa` ASC) VISIBLE,
  INDEX `fk_Empresas_Endereco1_idx` (`Endereco_idEndereco` ASC) VISIBLE,
  CONSTRAINT `fk_Empresas_Endereco1`
    FOREIGN KEY (`Endereco_idEndereco`)
    REFERENCES `IRRF`.`Endereco` (`idEndereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `IRRF`.`Fone_Contribuinte`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `IRRF`.`Fone_Contribuinte` ;

CREATE TABLE IF NOT EXISTS `IRRF`.`Fone_Contribuinte` (
  `Contribuinte_idContribuinte` INT NOT NULL,
  `Fones_idFone` INT NOT NULL,
  INDEX `fk_Fone_Contribuinte_Contribuinte1_idx` (`Contribuinte_idContribuinte` ASC) VISIBLE,
  INDEX `fk_Fone_Contribuinte_Fones1_idx` (`Fones_idFone` ASC) VISIBLE,
  CONSTRAINT `fk_Fone_Contribuinte_Contribuinte1`
    FOREIGN KEY (`Contribuinte_idContribuinte`)
    REFERENCES `IRRF`.`Contribuinte` (`idContribuinte`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Fone_Contribuinte_Fones1`
    FOREIGN KEY (`Fones_idFone`)
    REFERENCES `IRRF`.`Fones` (`idFone`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `IRRF`.`Fone_Empresa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `IRRF`.`Fone_Empresa` ;

CREATE TABLE IF NOT EXISTS `IRRF`.`Fone_Empresa` (
  `Fones_idFone` INT NOT NULL,
  `Empresas_idEmpresa` INT NOT NULL,
  INDEX `fk_Fone_Empresa_Fones1_idx` (`Fones_idFone` ASC) VISIBLE,
  INDEX `fk_Fone_Empresa_Empresas1_idx` (`Empresas_idEmpresa` ASC) VISIBLE,
  CONSTRAINT `fk_Fone_Empresa_Fones1`
    FOREIGN KEY (`Fones_idFone`)
    REFERENCES `IRRF`.`Fones` (`idFone`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Fone_Empresa_Empresas1`
    FOREIGN KEY (`Empresas_idEmpresa`)
    REFERENCES `IRRF`.`Empresas` (`idEmpresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `IRRF`.`Email_Contribuinte`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `IRRF`.`Email_Contribuinte` ;

CREATE TABLE IF NOT EXISTS `IRRF`.`Email_Contribuinte` (
  `Contribuinte_idContribuinte` INT NOT NULL,
  `idEmailContribuinte` INT NOT NULL AUTO_INCREMENT,
  `Email_Contribuinte` VARCHAR(255) NOT NULL UNIQUE,
  INDEX `fk_Email_Contribuinte_Contribuinte1_idx` (`Contribuinte_idContribuinte` ASC) VISIBLE,
  PRIMARY KEY (`idEmailContribuinte`),
  CONSTRAINT `fk_Email_Contribuinte_Contribuinte1`
    FOREIGN KEY (`Contribuinte_idContribuinte`)
    REFERENCES `IRRF`.`Contribuinte` (`idContribuinte`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `IRRF`.`Email_Empresa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `IRRF`.`Email_Empresa` ;

CREATE TABLE IF NOT EXISTS `IRRF`.`Email_Empresa` (
  `Empresas_idEmpresa` INT NOT NULL,
  `idEmailEmpresa` INT NOT NULL AUTO_INCREMENT,
  `Email_Empresa` VARCHAR(255) NOT NULL UNIQUE,
  INDEX `fk_Email_Empresa_Empresas1_idx` (`Empresas_idEmpresa` ASC) VISIBLE,
  PRIMARY KEY (`idEmailEmpresa`),
  CONSTRAINT `fk_Email_Empresa_Empresas1`
    FOREIGN KEY (`Empresas_idEmpresa`)
    REFERENCES `IRRF`.`Empresas` (`idEmpresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `IRRF`.`Rendimentos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `IRRF`.`Rendimentos` ;

CREATE TABLE IF NOT EXISTS `IRRF`.`Rendimentos` (
  `idRendimento` INT NOT NULL AUTO_INCREMENT,
  `nomeEmpresa` VARCHAR(255) NULL,
  `valorRecebido` DOUBLE NOT NULL,
  `INSS` DOUBLE NULL,
  `IRRFPago` DOUBLE NULL,
  `valor13Salario` DOUBLE NULL,
  `Empresas_cnpjEmpresa` VARCHAR(32) NOT NULL,
  `Contribuinte_cpfContribuinte` VARCHAR(16) NOT NULL,
  PRIMARY KEY (`idRendimento`),
  INDEX `fk_Rendimentos_Empresas1_idx` (`Empresas_cnpjEmpresa` ASC) VISIBLE,
  UNIQUE INDEX `Contribuinte_idContribuinte_UNIQUE` (`Contribuinte_cpfContribuinte` ASC) VISIBLE,
  CONSTRAINT `fk_Rendimentos_Empresas1`
    FOREIGN KEY (`Empresas_cnpjEmpresa`)
    REFERENCES `IRRF`.`Empresas` (`cnpjEmpresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Rendimentos_Contribuinte1`
    FOREIGN KEY (`Contribuinte_cpfContribuinte`)
    REFERENCES `IRRF`.`Contribuinte` (`cpfContribuinte`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `IRRF`.`TipoDireitoBens`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `IRRF`.`TipoDireitoBens` ;

CREATE TABLE IF NOT EXISTS `IRRF`.`TipoDireitoBens` (
  `idTipoDireitoBem` INT NOT NULL,
  `nomeDireitoBem` VARCHAR(255) NULL,
  `descricaoDireitoBem` VARCHAR(255) NULL,
  PRIMARY KEY (`idTipoDireitoBem`));


-- -----------------------------------------------------
-- Table `IRRF`.`DireitosBens`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `IRRF`.`DireitosBens` ;

CREATE TABLE IF NOT EXISTS `IRRF`.`DireitosBens` (
  `idDireitoBem` INT NOT NULL,
  `valorTotalDireitoBem` DOUBLE NULL,
  `TipoDireitoBem_idTipoDireitoBem` INT NOT NULL,
  `Contribuinte_cpfContribuinte` VARCHAR(16) NOT NULL,
  PRIMARY KEY (`idDireitoBem`),
  INDEX `fk_Direitos_TipoDireito1_idx` (`TipoDireitoBem_idTipoDireitoBem` ASC) VISIBLE,
  INDEX `fk_Direitos_Contribuinte1_idx` (`Contribuinte_cpfContribuinte` ASC) VISIBLE,
  CONSTRAINT `fk_Direitos_TipoDireito1`
    FOREIGN KEY (`TipoDireitoBem_idTipoDireitoBem`)
    REFERENCES `IRRF`.`TipoDireitoBens` (`idTipoDireitoBem`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Direitos_Contribuinte1`
    FOREIGN KEY (`Contribuinte_cpfContribuinte`)
    REFERENCES `IRRF`.`Contribuinte` (`cpfContribuinte`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `IRRF`.`tipoDependente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `IRRF`.`TiposDependente` ;

CREATE TABLE IF NOT EXISTS `IRRF`.`TiposDependente` (
  `idTipoDependente` INT NOT NULL AUTO_INCREMENT,
  `nomeTipoDependente` VARCHAR(16) NOT NULL UNIQUE,
  PRIMARY KEY (`idTipoDependente`));


-- -----------------------------------------------------
-- Table `IRRF`.`Dependentes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `IRRF`.`Dependentes` ;

CREATE TABLE IF NOT EXISTS `IRRF`.`Dependentes` (
  `idDependentes` INT NOT NULL AUTO_INCREMENT,
  `nomeDependente` VARCHAR(255) NULL,
  `sobrenomeDependente` VARCHAR(255) NULL,
  `nomeSocialDependente` VARCHAR(255) NULL,
  `cpfDependente` VARCHAR(16) NOT NULL,
  `rgDependente` VARCHAR(16) NULL,
  `sexoDependente` CHAR(1) NULL,
  `numeroEnderecoDependente` INT NULL,
  `complementoDependente` VARCHAR(255) NOT NULL,
  `Contribuinte_idContribuinte` INT NOT NULL,
  `TipoDependente_idTipoDependente` INT NOT NULL,
  `Endereco_idEndereco` INT NOT NULL,
  PRIMARY KEY (`idDependentes`),
  UNIQUE INDEX `cpfContribuinte_UNIQUE` (`cpfDependente` ASC) VISIBLE,
  INDEX `fk_Dependentes_Contribuinte1_idx` (`Contribuinte_idContribuinte` ASC) VISIBLE,
  INDEX `fk_Dependentes_tipoDependente1_idx` (`tipoDependente_idTipoDependente` ASC) VISIBLE,
  INDEX `fk_Dependentes_Endereco1_idx` (`Endereco_idEndereco` ASC) VISIBLE,
  CONSTRAINT `fk_Dependentes_Contribuinte1`
    FOREIGN KEY (`Contribuinte_idContribuinte`)
    REFERENCES `IRRF`.`Contribuinte` (`idContribuinte`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Dependentes_tipoDependente1`
    FOREIGN KEY (`tipoDependente_idTipoDependente`)
    REFERENCES `IRRF`.`tipoDependente` (`idTipoDependente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Dependentes_Endereco1`
    FOREIGN KEY (`Endereco_idEndereco`)
    REFERENCES `IRRF`.`Endereco` (`idEndereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `IRRF`.`Fone_Dependente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `IRRF`.`Fone_Dependente` ;

CREATE TABLE IF NOT EXISTS `IRRF`.`Fone_Dependente` (
  `Dependentes_idDependentes` INT NOT NULL,
  `Fones_idFone` INT NOT NULL,
  INDEX `fk_Fone_Dependente_Dependentes1_idx` (`Dependentes_idDependentes` ASC) VISIBLE,
  INDEX `fk_Fone_Dependente_Fones1_idx` (`Fones_idFone` ASC) VISIBLE,
  CONSTRAINT `fk_Fone_Dependente_Dependentes1`
    FOREIGN KEY (`Dependentes_idDependentes`)
    REFERENCES `IRRF`.`Dependentes` (`idDependentes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Fone_Dependente_Fones1`
    FOREIGN KEY (`Fones_idFone`)
    REFERENCES `IRRF`.`Fones` (`idFone`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `IRRF`.`Email_Dependente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `IRRF`.`Email_Dependente` ;

CREATE TABLE IF NOT EXISTS `IRRF`.`Email_Dependente` (
  `Dependentes_idDependentes` INT NOT NULL,
  `idEmailDependente` INT NOT NULL AUTO_INCREMENT,
  `Email_Dependente` VARCHAR(255) NOT NULL UNIQUE,
  INDEX `fk_Email_Dependente_Dependentes1_idx` (`Dependentes_idDependentes` ASC) VISIBLE,
  PRIMARY KEY (`idEmailDependente`),
  CONSTRAINT `fk_Email_Dependente_Dependentes1`
    FOREIGN KEY (`Dependentes_idDependentes`)
    REFERENCES `IRRF`.`Dependentes` (`idDependentes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
